Export `easystats_packages()`
easystats/easystats pull request #417
Opened 2024-06-08 19:53 UTC by etiennebacher

Close #411 

I also removed `.packages_on_github()` since it was equivalent to `.packages_on_cran()` and I think the likelihood of having another package (on Github only) is quite low

2024-06-08 20:32 UTC, IndrajeetPatil requested changes
Overall, LGTM. Thanks for working on this!

- Can you please also add a simple test? 
Maybe checking the length and the contents of the vector.

- Update pkgdown config file to also include this new function

2024-06-08 20:34 UTC, IndrajeetPatil commented on R/utils.R
> -.add_easystats_dev_pkgs <- function(out, easystats_not_on_cran) {
Yeah, I agree about getting rid of this. 

The only reason I had been hesitant to get rid of it thus far was `{circus}`, but that package is not really of any value or relevance to our users anyway.

2024-06-09 06:46 UTC, strengejacke commented
> I also removed .packages_on_github() since it was equivalent to .packages_on_cran() and I think the likelihood of having another package (on Github only) is quite low

Yes, this function had historical reasons, when not all packages were on CRAN. It's obsolete now.

2024-06-09 06:47 UTC, strengejacke approved these changes

2024-06-09 18:59 UTC, etiennebacher commented
Thanks for the review

> Can you please also add a simple test?

I don't see the point, this function just prints a hardcoded character vector, it's not like some internal code can modify its output.

> Update pkgdown config file to also include this new function

Thanks, I forgot about it. Done

2024-06-09 19:06 UTC, IndrajeetPatil commented
In that case, can you ignore directive for code coverage for the body of the function?

2024-06-09 19:14 UTC, IndrajeetPatil approved these changes

2024-06-09 19:19 UTC, etiennebacher commented
Any idea where this error comes from?

https://github.com/easystats/easystats/actions/runs/9438885978/job/25996361636?pr=417#step:6:68

2024-06-09 19:26 UTC, etiennebacher commented
Looks like this is related to `Matrix`: https://stackoverflow.com/a/77504843

Anyway, not related to this PR so merging

2024-06-09 19:27 UTC, merged